import { notFound } from "next/navigation";
import { Metadata } from "next";
import { AnimatedSection } from "@/components/AnimatedSection";
import { appData, getAppById } from "@/lib/appData";
import { Shield, ArrowLeft } from "lucide-react";
import Link from "next/link";

interface PrivacyPageProps {
    params: Promise<{ appName: string }>;
}

// Generate static paths for all apps
export async function generateStaticParams() {
    return appData.map((app) => ({
        appName: app.id,
    }));
}

// Generate metadata for each app's privacy page
export async function generateMetadata({
    params,
}: PrivacyPageProps): Promise<Metadata> {
    const { appName } = await params;
    const app = getAppById(appName);

    if (!app) {
        return {
            title: "Privacy Policy Not Found",
        };
    }

    return {
        title: `${app.name} Privacy Policy | Burak Savkli`,
        description: `Privacy Policy for ${app.name} - ${app.tagline}`,
    };
}

export default async function PrivacyPage({ params }: PrivacyPageProps) {
    const { appName } = await params;
    const app = getAppById(appName);

    if (!app) {
        notFound();
    }

    // Readnest-specific privacy policy
    if (app.id === "readnest") {
        return <ReadnestPrivacyPolicy appName={app.name} />;
    }

    // Generic fallback for other apps
    return <GenericPrivacyPolicy app={app} />;
}

function ReadnestPrivacyPolicy({ appName }: { appName: string }) {
    return (
        <div className="min-h-screen py-24 px-6">
            <div className="max-w-3xl mx-auto">
                {/* Back Link */}
                <AnimatedSection>
                    <Link
                        href="/"
                        className="inline-flex items-center gap-2 text-gray-600 hover:text-gray-900 transition-colors mb-8"
                    >
                        <ArrowLeft size={18} />
                        Back to Home
                    </Link>
                </AnimatedSection>

                {/* Header */}
                <AnimatedSection delay={0.1}>
                    <div className="mb-12">
                        <div className="inline-flex items-center gap-2 bg-emerald-50 text-emerald-700 px-4 py-2 rounded-full text-sm font-medium mb-6">
                            <Shield size={16} />
                            Privacy Policy
                        </div>
                        <h1 className="text-3xl sm:text-4xl md:text-5xl font-bold text-gray-900 mb-4">
                            {appName} Privacy Policy
                        </h1>
                        <p className="text-gray-500">Last Updated: December 19, 2025</p>
                    </div>
                </AnimatedSection>

                {/* Privacy Content */}
                <AnimatedSection delay={0.2}>
                    <div className="prose prose-gray max-w-none">
                        <p className="text-gray-600 leading-relaxed mb-8">
                            Readnest (&quot;we&quot;, &quot;our&quot;, or &quot;us&quot;) respects your privacy and is committed to protecting your personal data. This Privacy Policy explains how we collect, use, store, and protect your information when you use the Readnest mobile application (&quot;App&quot;).
                        </p>

                        {/* Section 1 */}
                        <section className="mb-8">
                            <h2 className="text-2xl font-semibold text-gray-900 mb-4">
                                1. Information We Collect
                            </h2>

                            <h3 className="text-lg font-medium text-gray-800 mb-3">1.1 Account Information</h3>
                            <p className="text-gray-600 leading-relaxed mb-2">When you create an account, we may collect:</p>
                            <ul className="list-disc list-inside text-gray-600 space-y-1 mb-4">
                                <li><strong>Email address</strong> (for email/password authentication)</li>
                                <li><strong>Authentication tokens</strong> (from Google or Apple Sign-In)</li>
                                <li><strong>User ID</strong> (unique identifier generated by our system)</li>
                            </ul>

                            <h3 className="text-lg font-medium text-gray-800 mb-3">1.2 User-Generated Content</h3>
                            <p className="text-gray-600 leading-relaxed mb-2">When you use the App, you may provide:</p>
                            <ul className="list-disc list-inside text-gray-600 space-y-1 mb-4">
                                <li><strong>Book library data</strong> (titles, authors, reading status, progress, genres)</li>
                                <li><strong>Notes</strong> (personal notes attached to books)</li>
                                <li><strong>Words/Vocabulary</strong> (words saved with definitions and translations)</li>
                                <li><strong>Highlights/Photos</strong> (images captured from books)</li>
                                <li><strong>Reading sessions</strong> (duration and date of focus timer sessions)</li>
                            </ul>

                            <h3 className="text-lg font-medium text-gray-800 mb-3">1.3 User Preferences</h3>
                            <p className="text-gray-600 leading-relaxed mb-2">We collect preferences you set within the App:</p>
                            <ul className="list-disc list-inside text-gray-600 space-y-1 mb-4">
                                <li><strong>Daily reading target</strong> (minutes per day)</li>
                                <li><strong>Preferred genres</strong> (book categories of interest)</li>
                                <li><strong>Reading goals</strong> (personal objectives)</li>
                                <li><strong>Translation language preferences</strong> (source and target languages)</li>
                                <li><strong>Onboarding completion status</strong></li>
                            </ul>

                            <h3 className="text-lg font-medium text-gray-800 mb-3">1.4 Subscription Information</h3>
                            <p className="text-gray-600 leading-relaxed mb-2">If you subscribe to premium features:</p>
                            <ul className="list-disc list-inside text-gray-600 space-y-1 mb-4">
                                <li><strong>Subscription plan type</strong> (monthly or yearly)</li>
                                <li><strong>Purchase date and status</strong></li>
                            </ul>

                            <h3 className="text-lg font-medium text-gray-800 mb-3">1.5 Technical Data</h3>
                            <p className="text-gray-600 leading-relaxed mb-2">We may automatically collect:</p>
                            <ul className="list-disc list-inside text-gray-600 space-y-1">
                                <li><strong>Device information</strong> (device type, operating system)</li>
                                <li><strong>IP address</strong> (for rate limiting of translation services)</li>
                            </ul>
                        </section>

                        {/* Section 2 */}
                        <section className="mb-8">
                            <h2 className="text-2xl font-semibold text-gray-900 mb-4">
                                2. How We Use Your Information
                            </h2>
                            <p className="text-gray-600 leading-relaxed mb-2">We use your information to:</p>
                            <ul className="list-disc list-inside text-gray-600 space-y-2">
                                <li><strong>Provide core functionality:</strong> Store and sync your book library, notes, words, and reading progress across devices</li>
                                <li><strong>Personalize your experience:</strong> Display recommended books based on your selected genres</li>
                                <li><strong>Enable translation services:</strong> Translate words to your preferred language using Google Cloud Translation API</li>
                                <li><strong>Track reading activity:</strong> Record focus timer sessions and maintain your reading streak</li>
                                <li><strong>Manage subscriptions:</strong> Process in-app purchases and determine feature access levels</li>
                                <li><strong>Improve our services:</strong> Analyze usage patterns to enhance the App</li>
                            </ul>
                        </section>

                        {/* Section 3 */}
                        <section className="mb-8">
                            <h2 className="text-2xl font-semibold text-gray-900 mb-4">
                                3. Data Storage and Security
                            </h2>

                            <h3 className="text-lg font-medium text-gray-800 mb-3">3.1 Data Storage</h3>
                            <ul className="list-disc list-inside text-gray-600 space-y-2 mb-4">
                                <li><strong>Cloud Storage:</strong> For authenticated users, data is stored securely on Supabase servers (hosted in secure data centers)</li>
                                <li><strong>Local Storage:</strong> For guest users, data is stored locally on your device using encrypted storage</li>
                                <li><strong>Photo Storage:</strong> User-uploaded images are stored in secure cloud storage buckets</li>
                            </ul>

                            <h3 className="text-lg font-medium text-gray-800 mb-3">3.2 Security Measures</h3>
                            <ul className="list-disc list-inside text-gray-600 space-y-2">
                                <li>All data transmissions are encrypted using HTTPS/TLS</li>
                                <li>Row-level security (RLS) policies ensure users can only access their own data</li>
                                <li>Authentication tokens are securely managed</li>
                                <li>Admin operations require service role authentication</li>
                            </ul>
                        </section>

                        {/* Section 4 */}
                        <section className="mb-8">
                            <h2 className="text-2xl font-semibold text-gray-900 mb-4">
                                4. Third-Party Services
                            </h2>
                            <p className="text-gray-600 leading-relaxed mb-4">We use the following third-party services:</p>

                            <h3 className="text-lg font-medium text-gray-800 mb-2">4.1 Supabase</h3>
                            <ul className="list-disc list-inside text-gray-600 space-y-1 mb-4">
                                <li><strong>Purpose:</strong> Authentication, database, and file storage</li>
                                <li><strong>Data Shared:</strong> Account information, user-generated content, photos</li>
                                <li><strong>Privacy Policy:</strong> <a href="https://supabase.com/privacy" className="text-amber-600 hover:text-amber-700" target="_blank" rel="noopener noreferrer">supabase.com/privacy</a></li>
                            </ul>

                            <h3 className="text-lg font-medium text-gray-800 mb-2">4.2 Google Books API</h3>
                            <ul className="list-disc list-inside text-gray-600 space-y-1 mb-4">
                                <li><strong>Purpose:</strong> Search and retrieve book information</li>
                                <li><strong>Data Shared:</strong> Search queries (book titles, authors)</li>
                                <li><strong>Privacy Policy:</strong> <a href="https://policies.google.com/privacy" className="text-amber-600 hover:text-amber-700" target="_blank" rel="noopener noreferrer">policies.google.com/privacy</a></li>
                            </ul>

                            <h3 className="text-lg font-medium text-gray-800 mb-2">4.3 Google Cloud Translation API</h3>
                            <ul className="list-disc list-inside text-gray-600 space-y-1 mb-4">
                                <li><strong>Purpose:</strong> Translate words and text</li>
                                <li><strong>Data Shared:</strong> Text submitted for translation, target language</li>
                                <li><strong>Privacy Policy:</strong> <a href="https://policies.google.com/privacy" className="text-amber-600 hover:text-amber-700" target="_blank" rel="noopener noreferrer">policies.google.com/privacy</a></li>
                            </ul>

                            <h3 className="text-lg font-medium text-gray-800 mb-2">4.4 Google OAuth / Apple Sign-In</h3>
                            <ul className="list-disc list-inside text-gray-600 space-y-1 mb-4">
                                <li><strong>Purpose:</strong> Secure authentication</li>
                                <li><strong>Data Shared:</strong> Authentication tokens only; we do not access your Google/Apple account data beyond basic profile information</li>
                                <li><strong>Privacy Policies:</strong> <a href="https://policies.google.com/privacy" className="text-amber-600 hover:text-amber-700" target="_blank" rel="noopener noreferrer">Google</a>, <a href="https://www.apple.com/legal/privacy/" className="text-amber-600 hover:text-amber-700" target="_blank" rel="noopener noreferrer">Apple</a></li>
                            </ul>

                            <h3 className="text-lg font-medium text-gray-800 mb-2">4.5 RevenueCat (Planned)</h3>
                            <ul className="list-disc list-inside text-gray-600 space-y-1">
                                <li><strong>Purpose:</strong> Subscription and in-app purchase management</li>
                                <li><strong>Data Shared:</strong> User ID, purchase history</li>
                                <li><strong>Privacy Policy:</strong> <a href="https://www.revenuecat.com/privacy" className="text-amber-600 hover:text-amber-700" target="_blank" rel="noopener noreferrer">revenuecat.com/privacy</a></li>
                            </ul>
                        </section>

                        {/* Section 5 */}
                        <section className="mb-8">
                            <h2 className="text-2xl font-semibold text-gray-900 mb-4">
                                5. Data Sharing and Disclosure
                            </h2>
                            <p className="text-gray-600 leading-relaxed mb-4">
                                We do <strong>not</strong> sell, rent, or trade your personal information to third parties.
                            </p>
                            <p className="text-gray-600 leading-relaxed mb-2">We may share your data only in the following circumstances:</p>
                            <ul className="list-disc list-inside text-gray-600 space-y-2">
                                <li><strong>With your consent:</strong> When you explicitly agree to share data</li>
                                <li><strong>For legal compliance:</strong> If required by law, court order, or government request</li>
                                <li><strong>To protect rights:</strong> To protect our rights, privacy, safety, or property</li>
                            </ul>
                        </section>

                        {/* Section 6 */}
                        <section className="mb-8">
                            <h2 className="text-2xl font-semibold text-gray-900 mb-4">
                                6. Data Retention
                            </h2>
                            <ul className="list-disc list-inside text-gray-600 space-y-2">
                                <li><strong>Active accounts:</strong> We retain your data for as long as your account is active</li>
                                <li><strong>Deleted accounts:</strong> When you delete your account, we permanently remove:
                                    <ul className="list-disc list-inside ml-6 mt-2 space-y-1">
                                        <li>All books, notes, words, and reading session data</li>
                                        <li>All uploaded photos from our storage</li>
                                        <li>Your user metadata and preferences</li>
                                        <li>Your authentication credentials</li>
                                    </ul>
                                </li>
                                <li><strong>Guest data:</strong> Guest data stored locally on your device is not automatically deleted; you can clear it by uninstalling the App or clearing app data</li>
                            </ul>
                        </section>

                        {/* Section 7 */}
                        <section className="mb-8">
                            <h2 className="text-2xl font-semibold text-gray-900 mb-4">
                                7. Your Rights and Choices
                            </h2>

                            <h3 className="text-lg font-medium text-gray-800 mb-3">7.1 Access and Portability</h3>
                            <p className="text-gray-600 leading-relaxed mb-4">You can view all your data within the App at any time.</p>

                            <h3 className="text-lg font-medium text-gray-800 mb-3">7.2 Account Deletion</h3>
                            <p className="text-gray-600 leading-relaxed mb-2">You can permanently delete your account and all associated data from within the App. This action is irreversible and removes:</p>
                            <ul className="list-disc list-inside text-gray-600 space-y-1 mb-4">
                                <li>All books in your library</li>
                                <li>All notes, words, and highlights</li>
                                <li>All uploaded photos</li>
                                <li>All reading session history</li>
                                <li>Your account credentials</li>
                            </ul>

                            <h3 className="text-lg font-medium text-gray-800 mb-3">7.3 Data Correction</h3>
                            <p className="text-gray-600 leading-relaxed mb-4">You can edit your books, notes, words, and preferences at any time within the App.</p>

                            <h3 className="text-lg font-medium text-gray-800 mb-3">7.4 Opt-Out Options</h3>
                            <ul className="list-disc list-inside text-gray-600 space-y-1">
                                <li>You can use the App as a guest without creating an account (with limited features)</li>
                                <li>You can choose not to provide optional information</li>
                            </ul>
                        </section>

                        {/* Section 8 */}
                        <section className="mb-8">
                            <h2 className="text-2xl font-semibold text-gray-900 mb-4">
                                8. Children&apos;s Privacy
                            </h2>
                            <p className="text-gray-600 leading-relaxed">
                                Readnest is not intended for children under the age of 13. We do not knowingly collect personal information from children under 13. If you believe we have inadvertently collected such information, please contact us so we can promptly delete it.
                            </p>
                        </section>

                        {/* Section 9 */}
                        <section className="mb-8">
                            <h2 className="text-2xl font-semibold text-gray-900 mb-4">
                                9. International Data Transfers
                            </h2>
                            <p className="text-gray-600 leading-relaxed">
                                If you access the App from outside the region where our servers are located, your information may be transferred to, stored, and processed in a different country. By using the App, you consent to such transfers.
                            </p>
                        </section>

                        {/* Section 10 */}
                        <section className="mb-8">
                            <h2 className="text-2xl font-semibold text-gray-900 mb-4">
                                10. Changes to This Policy
                            </h2>
                            <p className="text-gray-600 leading-relaxed mb-2">We may update this Privacy Policy from time to time. We will notify you of any significant changes by:</p>
                            <ul className="list-disc list-inside text-gray-600 space-y-1 mb-4">
                                <li>Posting the new Privacy Policy within the App</li>
                                <li>Updating the &quot;Last Updated&quot; date at the top</li>
                            </ul>
                            <p className="text-gray-600 leading-relaxed">
                                Your continued use of the App after changes are posted constitutes your acceptance of the modified Privacy Policy.
                            </p>
                        </section>

                        {/* Section 11 */}
                        <section className="mb-8">
                            <h2 className="text-2xl font-semibold text-gray-900 mb-4">
                                11. Contact Us
                            </h2>
                            <p className="text-gray-600 leading-relaxed">
                                If you have any questions, concerns, or requests regarding this Privacy Policy or our data practices, please contact us at:
                            </p>
                            <p className="text-gray-600 leading-relaxed mt-2">
                                <strong>Email:</strong>{" "}
                                <a
                                    href="mailto:uiconfig32@gmail.com"
                                    className="text-amber-600 hover:text-amber-700 font-medium"
                                >
                                    uiconfig32@gmail.com
                                </a>
                            </p>
                        </section>


                    </div>
                </AnimatedSection>
            </div>
        </div>
    );
}

function GenericPrivacyPolicy({ app }: { app: { name: string } }) {
    const lastUpdated = new Date().toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
    });

    return (
        <div className="min-h-screen py-24 px-6">
            <div className="max-w-3xl mx-auto">
                {/* Back Link */}
                <AnimatedSection>
                    <Link
                        href="/"
                        className="inline-flex items-center gap-2 text-gray-600 hover:text-gray-900 transition-colors mb-8"
                    >
                        <ArrowLeft size={18} />
                        Back to Home
                    </Link>
                </AnimatedSection>

                {/* Header */}
                <AnimatedSection delay={0.1}>
                    <div className="mb-12">
                        <div className="inline-flex items-center gap-2 bg-emerald-50 text-emerald-700 px-4 py-2 rounded-full text-sm font-medium mb-6">
                            <Shield size={16} />
                            Privacy Policy
                        </div>
                        <h1 className="text-3xl sm:text-4xl md:text-5xl font-bold text-gray-900 mb-4">
                            {app.name} Privacy Policy
                        </h1>
                        <p className="text-gray-500">Last updated: {lastUpdated}</p>
                    </div>
                </AnimatedSection>

                {/* Privacy Content */}
                <AnimatedSection delay={0.2}>
                    <div className="prose prose-gray max-w-none">
                        <section className="mb-8">
                            <h2 className="text-2xl font-semibold text-gray-900 mb-4">
                                Introduction
                            </h2>
                            <p className="text-gray-600 leading-relaxed">
                                Welcome to {app.name}. Your privacy is important to us. This
                                Privacy Policy explains how we collect, use, disclose, and
                                safeguard your information when you use our mobile application.
                                Please read this privacy policy carefully.
                            </p>
                        </section>

                        <section className="mb-8">
                            <h2 className="text-2xl font-semibold text-gray-900 mb-4">
                                Information We Collect
                            </h2>
                            <p className="text-gray-600 leading-relaxed mb-4">
                                We may collect information about you in a variety of ways. The
                                information we may collect via the Application includes:
                            </p>
                            <ul className="list-disc list-inside text-gray-600 space-y-2">
                                <li>
                                    <strong>Personal Data:</strong> Information you provide when
                                    creating an account, such as your name and email address.
                                </li>
                                <li>
                                    <strong>Usage Data:</strong> Information about how you use the
                                    app, including features accessed and time spent.
                                </li>
                                <li>
                                    <strong>Device Data:</strong> Information about your mobile
                                    device, including device type and operating system version.
                                </li>
                            </ul>
                        </section>

                        <section className="mb-8">
                            <h2 className="text-2xl font-semibold text-gray-900 mb-4">
                                Contact Us
                            </h2>
                            <p className="text-gray-600 leading-relaxed">
                                If you have any questions about this Privacy Policy, please
                                contact us through our{" "}
                                <Link
                                    href="/support"
                                    className="text-amber-600 hover:text-amber-700 font-medium"
                                >
                                    Support page
                                </Link>{" "}
                                or email us at{" "}
                                <a
                                    href="mailto:uiconfig32@gmail.com"
                                    className="text-amber-600 hover:text-amber-700 font-medium"
                                >
                                    uiconfig32@gmail.com
                                </a>
                                .
                            </p>
                        </section>
                    </div>
                </AnimatedSection>
            </div>
        </div>
    );
}
